export default {
  one: require("../assets/images/1.jpg"),
  two: require("../assets/images/2.jpg"),
  three: require("../assets/images/3.jpg"),
  four: require("../assets/images/4.jpg"),
  five: require("../assets/images/5.jpg"),
  six: require("../assets/images/6.jpg"),

  leftArrow: require("../assets/images/left-arrow-mouse.png"),
  leftArrow_hover: require("../assets/images/left-arrow.png"),
  rightArrow: require("../assets/images/right-arrow-mouse.png"),
  rightArrow_hover: require("../assets/images/right-arrow.png"),

  cuteDuck: require("../assets/images/cuteduck.jpg"),
  fishbowl: require("../assets/images/fishbowl.jpg"),

  sigong: require("../assets/images/sigong.png"),
  search: require("../assets/images/search.png"),
  hlaf_arrow: require("../assets/images/half-arrow.png"),
  phone: require("../assets/images/phone.png"),
  snsflag: require("../assets/images/snsflag.png"),
  sns: require("../assets/images/sns.jpg"),
  i_youtube: require("../assets/images/youtube.png"),
  i_naverBlog: require("../assets/images/naverBlog.png"),
  i_facebook: require("../assets/images/facebook.png"),
  i_kakaotalk: require("../assets/images/kakaotalk.png"),
  i_instagram: require("../assets/images/instagram.png"),
  i_icon: require("../assets/images/icon.png"),
  solution3: require("../assets/images/solution3.gif"),
  solution2: require("../assets/images/solution2.gif"),
  solution1: require("../assets/images/solution1.gif"),
  interior: require("../assets/images/interior.gif"),
  building: require("../assets/images/building.gif"),
  banner: require("../assets/images/banner.png"),

  request: require("../assets/images/request.png"),
  login: require("../assets/images/login.png"),
  categori: require("../assets/images/categori.png"),
};
